---
- name: Create Logstash configuration files.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 01-beats-input.conf
    - 30-elasticsearch-output.conf
  notify: restart logstash

- name: Create Logstash filters.
  template:
    src: "../../../files/logstash/filters/{{ item }}"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 12-receiver_access.conf
  notify: restart logstash

- name: Change logstash dirs permissions.
  file:
    path: "{{ item }}"
    owner: logstash
    group: logstash
    state: directory
    recurse: yes
  with_items:
    - "/usr/share/logstash"
    - "/var/log/logstash/"
    - "/var/lib/logstash/"
  notify: restart logstash
